### ISSUE TITLE
Checklist for new Projects

### ISSUE THREAD

**Issue by vknabel** [felix91gr/awesome-system-swift#7]
We should provide a checklist for new projects and the criteria they should fulfill (e.g. At least working on Linux compatability). 

Additionally PR and issue templates may be interesting.

**Comment by vknabel** [comment]
@felix91gr what do you think on this? Do you have ideas on relevant criteria besides (planned) linux support and requiring the projects to be maintained?

**Comment by felix91gr** [comment]
I agree with the three. A checklist is a really good idea, and PR templates as well. Issue templates are interesting, although atm I don't have a clear idea of how they could be.

Regarding the criterias, lemme see :thinking: 
* To have tests. Tests are so useful to know if the project has been ported correctly to the other platform, and to then keep it operational on both. 
OTOH, there are projects that don't have any tests, and if they are apps that might be allright. But for the case of libraries, I don't think I could even trust my own if I didn't have tests to back it up. How could I know that the most basic things still work?
So for libraries I'd put tests as a requirement.

Apart from that, I can't think of anything relevant right now. Maybe something's escaping me :thinking:

What are your thoughts on the checklist's requirements?

**Comment by vknabel** [comment]
> Issue templates are interesting, although atm I don't have a clear idea of how they could be.

Me neither, but I thougt you could have an idea.

> To have tests. 

This is actually obvious but it didn't come to my mind. (👍 for the reasoning)

A small and first concept for the PR template:

- [ ] Linux support is stable or at least planned
- [ ] Project is actively maintained
- [ ] For library: it should have unit tests

**Comment by felix91gr** [comment]
> Maybe we could add a notice regarding sorting?

Alphabetic sorting? Indeed, or we may forget (like in that last PR) :D

> And we should add the same criteria to the README as list as well.

:+1: 

I think the template concept looks pretty good. Wanna make it?

**Comment by felix91gr** [comment]
Made real by #9 :)
